version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    comands:
      - aws s3 cp --recursive ./build s3://travel-react
      - cp appspec.yml ./build/appspec.yml
      - echo Build completed on `date`

artifacts:
  files:
    - **/*
    - appspec.yml
    - scripts/**/*
